export default Object.freeze({
    createGarden: 'Create garden',
    updateGarden: 'Update garden',
    deleteGarden: 'Delete garden',
    addBed: 'Add bed',
    createNewGarden: 'Create a new garden',
    createNewBed: 'Create a new garden bed',
    length: 'Length',
    width: 'Width',
    ft: 'ft.',
    bedName: 'Bed Name',
    gardenName: 'Garden Name',
    letsStartGarden: "Let's start with the overall garden space",
    howBigIsGarden: 'How big is your garden space?',
    whereLocated: 'Where will your space be located?',
    letsAddToGarden: "Let's add beds to the garden space.",
    tellUsAboutBed: 'Tell us about one bed in the garden.',
    howMuchSun: 'How much sun will it receive?',
    howManyBeds: 'How many beds will be like this?',
    continueAddingBeds: 'Continue adding beds',
    beginFillingBeds: 'Begin filling beds',
    zipCode: 'Zip Code',
    whyWeAskForZip:
        'We ask for your zip code to find the length of your growing season',
    addNewGarden: 'Add New Garden',
    addBeds: 'Add Beds',
    plantBeds: 'Plant Beds',
    arrangeBeds: 'Arrange Beds',
    gardenDetails: 'Garden Details',
    gardenBeds: 'Garden Beds',
    whatCallGarden: 'What will you call this garden',
    hideCrops: 'Hide crops',
    showCrops: 'Show crops',
    pleaseSelectBed: 'Please select a bed',
    signInWithGoogle: 'Sign In With Google',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot password',
    confirmCode: 'Confirm a code',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    firstName: 'First Name',
    lastName: 'Last Name',
    logout: 'Logout',
    submit: 'Submit',
    resendCode: 'Resend code',
    backToSignup: 'Back to sign up',
    confirmationCode: 'Confirmation code',
    confirmYourAccount: 'Confirm Your Account',
    resetYourPassword: 'Reset Your Password',
    newPassword: 'New Password',
})
